package robhancdklibawsaps

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/robert-hanuschke/robhan-cdk-lib-aws-aps/robhancdklibawsaps/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/constructs-go/constructs/v10"
)

// The definition of a rule groups namespace in an Amazon Managed Service for Prometheus workspace.
//
// A rule groups namespace is associated with exactly one rules file. A workspace can have multiple
// rule groups namespaces.
type RuleGroupsNamespace interface {
	RuleGroupsNamespaceBase
	// The rules file used in the namespace.
	Data() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	Env() *awscdk.ResourceEnvironment
	// The name of the rule groups namespace.
	Name() *string
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// The workspace to add the rule groups namespace.
	RuleGroupsNamespaceArn() *string
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// The workspace to add the rule groups namespace.
	Workspace() IWorkspace
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for RuleGroupsNamespace
type jsiiProxy_RuleGroupsNamespace struct {
	jsiiProxy_RuleGroupsNamespaceBase
}

func (j *jsiiProxy_RuleGroupsNamespace) Data() *string {
	var returns *string
	_jsii_.Get(
		j,
		"data",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RuleGroupsNamespace) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RuleGroupsNamespace) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RuleGroupsNamespace) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RuleGroupsNamespace) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RuleGroupsNamespace) RuleGroupsNamespaceArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ruleGroupsNamespaceArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RuleGroupsNamespace) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_RuleGroupsNamespace) Workspace() IWorkspace {
	var returns IWorkspace
	_jsii_.Get(
		j,
		"workspace",
		&returns,
	)
	return returns
}


func NewRuleGroupsNamespace(scope constructs.Construct, id *string, props *RuleGroupsNamespaceProps) RuleGroupsNamespace {
	_init_.Initialize()

	if err := validateNewRuleGroupsNamespaceParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_RuleGroupsNamespace{}

	_jsii_.Create(
		"@robhan-cdk-lib/aws_aps.RuleGroupsNamespace",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewRuleGroupsNamespace_Override(r RuleGroupsNamespace, scope constructs.Construct, id *string, props *RuleGroupsNamespaceProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@robhan-cdk-lib/aws_aps.RuleGroupsNamespace",
		[]interface{}{scope, id, props},
		r,
	)
}

func RuleGroupsNamespace_FromRuleGroupsNamespaceAttributes(scope constructs.Construct, id *string, attrs *RuleGroupsNamespaceAttributes) IRuleGroupsNamespace {
	_init_.Initialize()

	if err := validateRuleGroupsNamespace_FromRuleGroupsNamespaceAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IRuleGroupsNamespace

	_jsii_.StaticInvoke(
		"@robhan-cdk-lib/aws_aps.RuleGroupsNamespace",
		"fromRuleGroupsNamespaceAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func RuleGroupsNamespace_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateRuleGroupsNamespace_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@robhan-cdk-lib/aws_aps.RuleGroupsNamespace",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func RuleGroupsNamespace_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateRuleGroupsNamespace_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@robhan-cdk-lib/aws_aps.RuleGroupsNamespace",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func RuleGroupsNamespace_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateRuleGroupsNamespace_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@robhan-cdk-lib/aws_aps.RuleGroupsNamespace",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func RuleGroupsNamespace_IsRuleGroupsNamespace(x interface{}) *bool {
	_init_.Initialize()

	if err := validateRuleGroupsNamespace_IsRuleGroupsNamespaceParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@robhan-cdk-lib/aws_aps.RuleGroupsNamespace",
		"isRuleGroupsNamespace",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func (r *jsiiProxy_RuleGroupsNamespace) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := r.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		r,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (r *jsiiProxy_RuleGroupsNamespace) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		r,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (r *jsiiProxy_RuleGroupsNamespace) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := r.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		r,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (r *jsiiProxy_RuleGroupsNamespace) GetResourceNameAttribute(nameAttr *string) *string {
	if err := r.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		r,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (r *jsiiProxy_RuleGroupsNamespace) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		r,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

