package robhancdklibawsaps

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/robert-hanuschke/robhan-cdk-lib-aws-aps/robhancdklibawsaps/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awskms"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces"
	"github.com/aws/constructs-go/constructs/v10"
)

type Workspace interface {
	WorkspaceBase
	// The alert manager definition, a YAML configuration for the alert manager in your Amazon Managed Service for Prometheus workspace.
	AlertManagerDefinition() *string
	// The alias that is assigned to this workspace to help identify it.
	//
	// It does not need to be
	// unique.
	Alias() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed in a Stack (those created by
	// creating new class instances like `new Role()`, `new Bucket()`, etc.), this
	// is always the same as the environment of the stack they belong to.
	//
	// For referenced resources (those obtained from referencing methods like
	// `Role.fromRoleArn()`, `Bucket.fromBucketName()`, etc.), they might be
	// different than the stack they were imported into.
	Env() *interfaces.ResourceEnvironment
	// The customer managed AWS KMS key to use for encrypting data within your workspace.
	KmsKey() awskms.IKey
	// Contains information about the current rules and alerting logging configuration for the workspace.
	//
	// Note: These logging configurations are only for rules and alerting logs.
	LoggingConfiguration() *LoggingConfiguration
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// The Prometheus endpoint available for this workspace..
	PrometheusEndpoint() *string
	// The definition of logging configuration in an Amazon Managed Service for Prometheus workspace.
	QueryLoggingConfiguration() *QueryLoggingConfiguration
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// The ARN of the workspace.
	WorkspaceArn() *string
	// Use this structure to define label sets and the ingestion limits for time series that match label sets, and to specify the retention period of the workspace.
	WorkspaceConfiguration() *WorkspaceConfiguration
	// The unique ID for the workspace.
	WorkspaceId() *string
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	GetWorkspaceId(workspaceArn *string) *string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for Workspace
type jsiiProxy_Workspace struct {
	jsiiProxy_WorkspaceBase
}

func (j *jsiiProxy_Workspace) AlertManagerDefinition() *string {
	var returns *string
	_jsii_.Get(
		j,
		"alertManagerDefinition",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Workspace) Alias() *string {
	var returns *string
	_jsii_.Get(
		j,
		"alias",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Workspace) Env() *interfaces.ResourceEnvironment {
	var returns *interfaces.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Workspace) KmsKey() awskms.IKey {
	var returns awskms.IKey
	_jsii_.Get(
		j,
		"kmsKey",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Workspace) LoggingConfiguration() *LoggingConfiguration {
	var returns *LoggingConfiguration
	_jsii_.Get(
		j,
		"loggingConfiguration",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Workspace) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Workspace) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Workspace) PrometheusEndpoint() *string {
	var returns *string
	_jsii_.Get(
		j,
		"prometheusEndpoint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Workspace) QueryLoggingConfiguration() *QueryLoggingConfiguration {
	var returns *QueryLoggingConfiguration
	_jsii_.Get(
		j,
		"queryLoggingConfiguration",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Workspace) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Workspace) WorkspaceArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"workspaceArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Workspace) WorkspaceConfiguration() *WorkspaceConfiguration {
	var returns *WorkspaceConfiguration
	_jsii_.Get(
		j,
		"workspaceConfiguration",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Workspace) WorkspaceId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"workspaceId",
		&returns,
	)
	return returns
}


func NewWorkspace(scope constructs.Construct, id *string, props *WorkspaceProps) Workspace {
	_init_.Initialize()

	if err := validateNewWorkspaceParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_Workspace{}

	_jsii_.Create(
		"@robhan-cdk-lib/aws_aps.Workspace",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewWorkspace_Override(w Workspace, scope constructs.Construct, id *string, props *WorkspaceProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@robhan-cdk-lib/aws_aps.Workspace",
		[]interface{}{scope, id, props},
		w,
	)
}

func Workspace_FromWorkspaceAttributes(scope constructs.Construct, id *string, attrs *WorkspaceAttributes) IWorkspace {
	_init_.Initialize()

	if err := validateWorkspace_FromWorkspaceAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IWorkspace

	_jsii_.StaticInvoke(
		"@robhan-cdk-lib/aws_aps.Workspace",
		"fromWorkspaceAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func Workspace_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateWorkspace_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@robhan-cdk-lib/aws_aps.Workspace",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func Workspace_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateWorkspace_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@robhan-cdk-lib/aws_aps.Workspace",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func Workspace_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateWorkspace_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@robhan-cdk-lib/aws_aps.Workspace",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func Workspace_IsWorkspace(x interface{}) *bool {
	_init_.Initialize()

	if err := validateWorkspace_IsWorkspaceParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@robhan-cdk-lib/aws_aps.Workspace",
		"isWorkspace",
		[]interface{}{x},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_Workspace) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := w.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (w *jsiiProxy_Workspace) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		w,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (w *jsiiProxy_Workspace) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := w.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		w,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_Workspace) GetResourceNameAttribute(nameAttr *string) *string {
	if err := w.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		w,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_Workspace) GetWorkspaceId(workspaceArn *string) *string {
	if err := w.validateGetWorkspaceIdParameters(workspaceArn); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		w,
		"getWorkspaceId",
		[]interface{}{workspaceArn},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_Workspace) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		w,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

